### ISSUE TITLE
add notes for installing curl from brew on OSX

### ISSUE THREAD

**Issue by polvi** [coreos/etcd-ca#17]
Brew has an update to date version of curl that can be used with TLS 1.2

**Comment by jakedt** [comment]
I found out a solution using the mac osx keychain for client certs. You can use openssl to convert the .crt and .key to a bundle in the pkcs12 format like so:

```
openssl pkcs12 -export -in etcdclient.crt -inkey etcdclient.key.insecure -out etcdclient.p12 -name "etcdclient"
```

To avoid confusion, name it with the same SAN you gave when you created the cert. When you import the .p12 file it will create a certificate named with the SAN, and a private key with the name given above.

Once you have the .p12 file, import that into the OSX keychain using Keychain Access. Then you can reference the key name with curl like so:

```
curl --cert "etcdclient" https://127.0.0.1:4001/v2/machines -v
```

In the command above I don't specify the CA for the server, since I also imported that into my keychain.
